baseURL                          = "https://imjeremy.com" # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                     # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                     # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "auto"                  # Choose "light" or "dark" or "auto"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = true                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = ""   # E-mail address for contact section
    customCSS                    = ["css/custom.css"]             # Include custom css files placed under assets/
    # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/
    # plausible                  = true                    # Use Plausible analytics (requires an account at Plausible.io)

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = false                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = false                    # show all posts in an archive format
        numberOfProjectsToShow   = 4                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = false                    # Show your current local time in contact section
        timeZone                 = "Australia/Melbourne"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-AU"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = true                   # Use a layout with two columns instead of three
    [params.kitchen]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        pinterest                = false

    # To enable giscus, the GitHub-discussions-based comment section,
    # input the repository for the discussions below. For more details, see
    # https://www.joelnitta.com/posts/2021-11-24_using-giscus/
    # and https://github.com/giscus/giscus
    [params.giscus]
        # repo = "github-user/github-repo" # Entering repo will enable giscus
        repo-id = "enter-repo-id"
        category = "Comments"
        category-id = "enter-category-id"
        mapping = "pathname"
        reactions-enabled = "1"
        emit-metadata = "0"
        theme = "dark"
        lang = "en"

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://lichess.org/?user=Saweeet#friend"
        icon  = "chess-knight" # icon name without the 'fa-'
        icon_pack = "fa"
    [[params.social]]
        url   = "https://twitter.com/sahweeet"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.twitch.tv/jezako"
        icon  = "twitch" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.instagram.com/jezsayinhi"
        icon  = "instagram" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = "rel=\"me\"" # Add rel attribute for Mastodon profile link verification
    [[params.social]]
        url   = "mailto:hello@imjeremy.com"
        icon  = "envelope" # icon name without the 'fa-'
        icon_pack = "fa"



# If you don't want to use the default menu, you can define one by yourself
 [[menu.main]]
     name    = "Home"
     url     = "/"
     weight  = 1
 [[menu.main]]
     name    = "whoami"
     url     = "/#about"
     weight  = 1
 [[menu.main]]
     name    = "Theology"
     url     = "/theology/"
     weight  = 4
 [[menu.main]]
      name    = "Projects"
      url     = "/projects/"
      weight  = 5
  [[menu.main]]
       name    = "Kitchen"
       url     = "/kitchen/"
       weight  = 5
  [[menu.main]]
       name    = "Connect"
       url     = "/#contact"
       weight  = 7

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    # noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "solarized-dark"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "imjeremy"
        [languages.en.params]
            description  = "My journey and reflective thoughts"   # Max 160 characters show in search results
            # footerText   = ""                      # Text to override default footer text (markdown allowed)
